name: test
on: [push]

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
      - run: go mod download
      - run: go test .
